services:
  llama:
    command:
      - '-m'
      - /models/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-Q8_0.gguf
      - '--mmproj'
      - /models/mmproj-Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-f16.gguf
      - '--alias'
      - Qwen3.5
      - '--host'
      - 0.0.0.0
      - '--port'
      - '8080'
      - '-ngl'
      - '99'
      - '-t'
      - '7'
      - '-c'
      - '262144'
      - '-b'
      - '512'
      - '-ub'
      - '1024'
      - '--parallel'
      - '3'
      - '-fa'
      - 'on'
      - '--jinja'
      - '--keep'
      - '1024'
      - '--swa-full'
      - '--no-context-shift'
      - '--chat-template-kwargs'
      - '{"enable_thinking": false}'
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 28000M
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      GGML_HIP_FORCE_MMQ: 1
      GGML_HIP_NO_VMM: 1
      GGML_HIP_PINNED_MEM: 0
      HIP_VISIBLE_DEVICES: 0,1
      HSA_OVERRIDE_GFX_VERSION: 9.0.6
      TZ: America/Los_Angeles
    group_add:
      - 44
      - 107
      - 568
    image: amstel8/llama-rocm:gfx906-rocm721-u24
    platform: linux/amd64
    ports:
      - '11434:8080'
    restart: unless-stopped
    volumes:
      - /mnt/ssd/speed/ai:/models
