services:
  llama-claud:
    image: amstel8/llama-rocm:gfx906-rocm721
    platform: linux/amd64
    command:
      - '-m'
      - /models/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf
      - '--host'
      - 0.0.0.0
      - '--port'
      - '8080'
      - '-ngl'
      - '99'
      - '-t'
      - '10'
      - '-c'
      - '131072'
      - '-b'
      - '512'
      - '-ub'
      - '1024'
      - '--parallel'
      - '1'
      - '-fa'
      - 'on'
      - '--jinja'
      - '--keep'
      - '1024'
      - '--swa-full'
      - '--no-context-shift'
      - '--chat-template-kwargs'
      - '{"enable_thinking": false}'
      - '--repeat-penalty'
      - '1.1'
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: 36000M
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      GGML_HIP_FORCE_MMQ: 1
      GGML_HIP_NO_VMM: 1
      GGML_HIP_PINNED_MEM: 0
      HIP_VISIBLE_DEVICES: 0
      HSA_OVERRIDE_GFX_VERSION: 9.0.6
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Los_Angeles
    group_add:
      - 44
      - 107
      - 568
    ports:
      - "11434:8080"
    volumes:
      - /mnt/bamboo/smb/ai:/models
    restart: unless-stopped